# Site settings
title: git-secret
email: mail@sobolevn.me
description: Shell scripts to encrypt your private data inside a git repository.
baseurl: "/git-secret" # the subpath of your site, e.g. /blog
url: "sobolevn.me" # the base hostname & protocol for your site

# GitHub links:
github_username: sobolevn
github_changelog: "https://github.com/sobolevn/git-secret/blob/master/CHANGELOG.md"

# Seo settings:
plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
